### ISSUE TITLE
Missing "aarch64/tcg-target.c" file.

### ISSUE THREAD

**Issue by pttuan** [ardbiesheuvel/X86EmulatorPkg#1]
In tcg.c, 
#include "aarch64/tcg-target.c"

But I don't see tcg-target.c/h in the source. Did you miss checking them?

Thanks,

**Comment by agraf** [comment]
We left those out on purpose, because they were the only GPL files in the tree. We did however work with the author of them to relicense them as LGPL, so that there is no legal barrier to include the emulator into proprietary firmware.

In the meantime, that submission happened, so be assured you'll have a working tree in a short while.

**Comment by agraf** [comment]
In fact, I just committed all the changes you need :).

**Comment by pttuan** [comment]
Great! Thanks :)
